kind: Deployment
apiVersion: apps/v1
metadata:
  name: sinfcloud-postgres
  namespace: sinfcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinfcloud-postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sinfcloud-postgres
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-ipypof
          persistentVolumeClaim:
            claimName: sincloud-pvc
      containers:
        - name: sinfcloud-postgres
          image: hub.sinfcloud.com/sinfcloud/sinfcloud-postgres:2.1.0
          ports:
            - name: http-0
              containerPort: 5432
              protocol: TCP
          resources: { }
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: volume-ipypof
              mountPath: /var/lib/postgresql/data/pgdata
              subPath: postgres/data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# 创建对应的端口映射
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sinfcloud-postgres
  name: sinfcloud-postgres
  namespace: sinfcloud
spec:
  ports:
    - name: port-postgres-5432
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30010
  selector:
    #指定服务名称
    app: sinfcloud-postgres
  sessionAffinity: None
  type: NodePort